/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercise_week6;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeAll;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)

public class AppTest {
    private App appUnderTest;

    @BeforeAll
    void setUp() {
        appUnderTest = new App();
    }

    @Test
    void inverseArray_arrayWithPremitiveInt_returnInversedArray() {
        int[] a = { 1, 4, 5, 8, 0, 2, 3, 1, 6 };
        int[] inversed = { 6, 1, 3, 2, 0, 8, 5, 4, 1 };
        int[] result = appUnderTest.inverse2(a);
        assertArrayEquals(inversed, result);

        // Exercise 7
    }

    @Test
    void concatenatesString_2Strings_returnAString() {
        assertTrue("ascd".equals(appUnderTest.concatenates("as", "cd")));
    }

    @Test
    void doubleInt_oddInt_returnDoubleofOdd() {
        assertEquals(10, appUnderTest.playNumber(5));
    }

    @Test
    void squareInt_evenInt_returnSquaredInt() {
        assertEquals(64, appUnderTest.playNumber(8));
    }

    @Test
    void countDiv2_positiveInteger_returnCount() {
        assertEquals(1, appUnderTest.divNum(-2));
    }

    @Test
    void reverseInt_positiveInteger_returnReverse() {
        assertEquals(-1731, appUnderTest.reverseNum(-1371));
    }

    @Test
    void sort_array_returnFromSmallToLarge() {
        int[] orginal = { 12, 4, 6, 2, 7, 3, 12 };
        int[] sorted = { 2, 3, 4, 6, 7, 12, 12 };
        assertArrayEquals(sorted, App.bubbleSort(orginal));
    }

    @Test
    void findMin_intArray_returnMinInt() {
        int[] array = { 10, 20, 0, -3, -100 };
        assertEquals(-100, App.min(array, 5));
    }
}
