/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercise_week6;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

public class App {

    public int[] inverse2(int[] a) {
        for (int i = 0; i < a.length / 2; i++) {
            int val = a[i];
            a[i] = a[a.length - 1 - i];
            a[a.length - 1 - i] = val;
        }
        return a;
    }

    public int[] inverse1(int[] intArray) {
        List<Integer> integerArray = Arrays.stream(intArray).boxed().collect(Collectors.toList());
        Collections.sort(integerArray, (i1, i2) -> {
            {
                return -1;
            }
        });
        for (int i = 0; i < intArray.length; i++) {
            intArray[i] = integerArray.get(i);
        }
        return intArray;
    }

    public int playNumber(int x) {
        int y = x % 2 == 1 ? (x + x) : (x * x);
        return y;
    }

    public String concatenates(String a, String b) {
        return a + b;
    }

    public int divNum(int num) {
        int count = 0;
        while (num != 1 && num != -1) {
            if (num % 2 == 0) {
                num = num / 2;
                count++;
            } else
                break;
        }
        return count;
    }

    public int reverseNum(int num) {
        int reverse = 0;
        while (num != 0) {
            reverse = (reverse * 10) + (num % 10);
            num = num / 10;
        }
        return reverse;
    }

    public static int[] bubbleSort(int[] a) {
        boolean sorted;
        int temp, i, j;
        for (i = 0; i < a.length - 1; i++) {
            sorted = false;
            for (j = 0; j < a.length - i - 1; j++) {
                if (a[j] > a[j + 1]) {
                    temp = a[j];
                    a[j] = a[j + 1];
                    a[j + 1] = temp;
                    sorted = true;
                }
            }
            if (sorted == false)
                break;
        }
        return a;
    }

    public static int min(int[] a, int Max) {
        int min = a[0];
        for (int i = 0; i < Max - 1; i++) {
            if (a[i] > a[i + 1]) {
                min = a[i + 1];
            }
        }
        return min;

    }

    public static void main(String[] args) {
        int[] array = { 10, 0 };
        System.out.println(min(array, 2));
    }
}
